# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build SSDT Project

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  DACPAC_NAME: AdventureWorks2019.dacpac
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  CONNECTIONSQL: ${{ secrets.CONNECTIONSQL }}

permissions:
  contents: read
  packages: write  # Added for publishing to GitHub Packages

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: SSDT-ARTIFAC
        path: bin/${{env.BUILD_CONFIGURATION}}/${{env.DACPAC_NAME}}
        retention-days: 30

  docker:
      needs: build
      runs-on: linux-virtual-saurabh

      steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: SSDT-ARTIFAC
          path: bin/Release
    
      - name: Build Docker image
        run: docker build -f Docker/adventureworks.dockerfile -t saurabhadventureworks:latest .

      - name: Tag image for ACR
        if: ${{ env.ACR_NAME != '' }}
        run: |
          REGISTRY="${{ env.ACR_NAME }}.azurecr.io"
          echo "Tagging for registry: $REGISTRY"
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:latest
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.run_number }}
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.sha }}


      - name: Log in to Azure Container Registry
        if: ${{ env.ACR_NAME != '' && env.ACR_USERNAME != '' && env.ACR_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Push image to ACR
        if: ${{  env.ACR_NAME != '' && (env.ACR_USERNAME != '' && env.ACR_PASSWORD != '') }}
        run: |
          REGISTRY="${{ env.ACR_NAME }}.azurecr.io"
          echo "Pushing to registry: $REGISTRY"
          docker push $REGISTRY/saurabhadventureworks:latest
          docker push $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.run_number }}
          docker push $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.sha }}

      - name: Logout from Azure Container Registry
        if: ${{ env.ACR_NAME != '' && env.ACR_USERNAME != '' && env.ACR_PASSWORD != '' }}
        run: docker logout ${{ env.ACR_NAME }}.azurecr.io

      # Generating the Package to publish on GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image for GHCR
        run: |
          REGISTRY="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "Tagging for registry: $REGISTRY"
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:latest
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.run_number }}
          docker tag saurabhadventureworks:latest $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.sha }}

      - name: Push image to GHCR
        run: |
          REGISTRY="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "Pushing to registry: $REGISTRY"
          docker push $REGISTRY/saurabhadventureworks:latest
          docker push $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.run_number }}
          docker push $REGISTRY/saurabhadventureworks:${{ github.ref_name }}.${{ github.sha }}

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io  
        
  deploy:
    needs: docker
    runs-on: window-virtual-saurabh  # Assumes 'window-virtual-saurabh' is your self-hosted runner name

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull latest image from GHCR
      run: |
        $repo = "${{ github.repository }}"
        $REGISTRY = "ghcr.io/$($repo.ToLower())"
        docker pull $REGISTRY/saurabhadventureworks:latest

    - name: Run the container
      run: |
        $repo = "${{ github.repository }}"
        $REGISTRY = "ghcr.io/$($repo.ToLower())"
        docker run -d --name sqlserver -p 1433:1433 -e SECRET_DATA="${{ env.CONNECTIONSQL }}" -e TENANT_CODE="voyager" -e TENANT_ID="8f7aad84-7e54-4987-ae11-0b0aa9159f57" -e LCR_ENV="sbox" -e LCR_GEO="eus" --rm -it "$REGISTRY/saurabhadventureworks:latest"
      # Note: Adjust environment variables (e.g., SA_PASSWORD) as needed for SQL Server. Ensure the Dockerfile sets up SQL Server correctly.

    - name: Wait for container to finish and remove image
      run: |
        $repo = "${{ github.repository }}"
        $REGISTRY = "ghcr.io/$($repo.ToLower())"
        # Wait for the container to stop (adjust timeout as needed)
        docker wait sqlserver
        # Remove the image after container execution
        docker rmi $REGISTRY/saurabhadventureworks:latest

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io